name: Build ZMK Firmware

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:stable
    strategy:
      fail-fast: false
      matrix:
        board: ["nice_nano_v2"]
        shield: ["sofle_left", "sofle_right"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'config'

      - name: West Init
        run: west init -l config

      - name: West Update
        run: west update

      - name: West Build
        run: |
          cd zmk/app
          west build -b ${{ matrix.board }} -- -DSHIELD=${{ matrix.shield }}

      - name: Rename firmware
        run: |
          cd zmk/app/build/zephyr
          mv zmk.uf2 ${{ matrix.shield }}_${{ matrix.board }}.uf2

      - name: Archive firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}-${{ matrix.shield }}
          path: zmk/app/build/zephyr/${{ matrix.shield }}_${{ matrix.board }}.uf2
          retention-days: 7
